### ISSUE TITLE
App crashes on heroku cedar-14

### ISSUE THREAD

**Issue by rossta** [jimmynicol/image-resizer#28]
First, thanks for the project! Set up went smoothly locally. Deploying to a new heroku stack, the app crashes on the following exception when attempting to process an image located on S3:

     2015-01-08T03:29:00.941788+00:00 app[web.1]:
     2015-01-08T03:29:00.941890+00:00 app[web.1]: events.js:72
     2015-01-08T03:29:00.942194+00:00 app[web.1]:         throw er; // Unhandled 'error' event
     2015-01-08T03:29:00.942204+00:00 app[web.1]:               ^
     2015-01-08T03:29:00.943546+00:00 app[web.1]:     at errnoException (net.js:905:11)
     2015-01-08T03:29:00.943543+00:00 app[web.1]: Error: write EPIPE
     2015-01-08T03:29:00.943547+00:00 app[web.1]:     at Object.afterWrite (net.js:721:19)
     2015-01-08T03:29:00.956264+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/photos/xxx.jpeg" host=xxx.herokuapp.com request_id=4005667b-9566-48f3-8dbd-0be72fe997c3 fwd="66.65.172.88" dyno=web.1 connect=7ms service=163ms status=503 bytes=0
     2015-01-08T03:29:01.691755+00:00 heroku[web.1]: Process exited with status 8
     2015-01-08T03:29:01.707579+00:00 heroku[web.1]: State changed from up to crashed

I suspect this error is being raised during processing by `graphicsmagick` (similar exception to this issue https://github.com/aheckmann/gm/issues/68) but I don't know enough yet to debug.

After switching to the deprecated cedar stack, `heroku stack:set cedar` and redeploying, images process and render just fine. 

Let me know if you have ideas on how to debug or need more info.

**Comment by jimmynicol** [comment]
Thanks for your kind words @rossta I am glad you like it!

So unfortunately this appears to be the problem: https://github.com/mcollina/heroku-buildpack-imagemagick/issues/9

I am searching around for some solutions, will post back when I get it working. Just to clarify I see the same issue in a fresh deployment.

**Comment by jimmynicol** [comment]
One thing I am strongly considering is moving off of `gm` as the resize engine in favour of [`sharp`](https://github.com/lovell/sharp). 

It looks like cedar-14 was also an issue for them but they have released a [fix for it]( https://github.com/alex88/heroku-buildpack-vips/issues/9).

Anyway I have been meaning to kick the tyres with `sharp` as if the README is to be believed it is orders of magnitude faster than `gm` and doesnt write out to temp files. So it should in theory be a much better fit for heroku dynos. 

I should have time over the weekend to give this a go.

**Comment by jimmynicol** [comment]
Lots more updates to the `sharp` branch if you are interested in checking them out. Very close to releasing them.

**Comment by jimmynicol** [comment]
Just landed `v1.0.0` using the sharp engine which is compatible with cedar-14 and is considerably faster. Give it a go, tell me what you think.
